language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script: pytest # run tests
after_success:
  - codecov # submit coverage
